version: "3"

dotenv: [".env", "{{.ENV}}/.env.", "{{.HOME}}/.env"]

tasks:
  types:
    cmds:
      - echo "Generating types... 🔄"
      - supabase gen types typescript --project-id $SUPABASE_PROJECT_ID > src/types/database.ts
      - echo "Types generated successfully ✅"
    silent: true

  dev:
    deps:
      - types
    cmds:
      - bun run dev
    silent: true
